# Script para criar dados hierárquicos para teste
import json

dados_hierarquicos = {
    "empresas": [
        # ABC Indústria - 3 setores, 3 cargos cada
        {"empresa": "ABC Indústria", "setor": "Produção", "cargo": "Operador", "atividade": "Operação de máquinas", "ambiente": "Chão de fábrica", "agentes": [{"agente": "Ruído", "concentracao": "85 dB", "exposicao": "8h", "analise": "Alto", "medidas_existentes": "EPI", "medidas_necessarias": "Isolamento"}], "parecer": "Necessário controle", "responsavel": "Eng. João Silva - CREA 12345-SP", "data_criacao": "15/12/2024 10:00:00"},
        {"empresa": "ABC Indústria", "setor": "Produção", "cargo": "Supervisor", "atividade": "Supervisão da produção", "ambiente": "Escritório na fábrica", "agentes": [{"agente": "Ruído", "concentracao": "75 dB", "exposicao": "6h", "analise": "Médio", "medidas_existentes": "Isolamento", "medidas_necessarias": "Monitoramento"}], "parecer": "Situação controlada", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:01:00"},
        {"empresa": "ABC Indústria", "setor": "Produção", "cargo": "Técnico", "atividade": "Manutenção de equipamentos", "ambiente": "Área de máquinas", "agentes": [{"agente": "Vibração", "concentracao": "2.5 m/s²", "exposicao": "4h", "analise": "Alto", "medidas_existentes": "Luvas", "medidas_necessarias": "Rodízio"}], "parecer": "Atenção especial", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:02:00"},
        
        {"empresa": "ABC Indústria", "setor": "Qualidade", "cargo": "Inspetor", "atividade": "Inspeção de produtos", "ambiente": "Laboratório", "agentes": [{"agente": "Iluminação", "concentracao": "500 lux", "exposicao": "8h", "analise": "Adequado", "medidas_existentes": "Iluminação LED", "medidas_necessarias": "Manutenção"}], "parecer": "Condições adequadas", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:03:00"},
        {"empresa": "ABC Indústria", "setor": "Qualidade", "cargo": "Analista", "atividade": "Análise de materiais", "ambiente": "Laboratório químico", "agentes": [{"agente": "Vapores", "concentracao": "10 ppm", "exposicao": "6h", "analise": "Controlado", "medidas_existentes": "Capela", "medidas_necessarias": "Monitoramento"}], "parecer": "Sistema eficiente", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:04:00"},
        {"empresa": "ABC Indústria", "setor": "Qualidade", "cargo": "Coordenador", "atividade": "Coordenação da qualidade", "ambiente": "Escritório", "agentes": [{"agente": "Ergonomia", "concentracao": "N/A", "exposicao": "8h", "analise": "Bom", "medidas_existentes": "Mobiliário ergonômico", "medidas_necessarias": "Ginástica laboral"}], "parecer": "Ambiente saudável", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:05:00"},
        
        {"empresa": "ABC Indústria", "setor": "Manutenção", "cargo": "Mecânico", "atividade": "Manutenção mecânica", "ambiente": "Oficina", "agentes": [{"agente": "Óleo", "concentracao": "5 mg/m³", "exposicao": "8h", "analise": "Controlado", "medidas_existentes": "Ventilação", "medidas_necessarias": "EPI adequado"}], "parecer": "Controle efetivo", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:06:00"},
        {"empresa": "ABC Indústria", "setor": "Manutenção", "cargo": "Eletricista", "atividade": "Manutenção elétrica", "ambiente": "Painéis elétricos", "agentes": [{"agente": "Choque elétrico", "concentracao": "220V", "exposicao": "4h", "analise": "Risco", "medidas_existentes": "EPI isolante", "medidas_necessarias": "Treinamento NR-10"}], "parecer": "Necessário treinamento", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:07:00"},
        {"empresa": "ABC Indústria", "setor": "Manutenção", "cargo": "Soldador", "atividade": "Soldagem e reparo", "ambiente": "Área de soldagem", "agentes": [{"agente": "Fumos metálicos", "concentracao": "3 mg/m³", "exposicao": "6h", "analise": "Alto", "medidas_existentes": "Exaustão", "medidas_necessarias": "Melhoria do sistema"}], "parecer": "Requer atenção", "responsavel": "Eng. Silva", "data_criacao": "15/12/2024 10:08:00"},

        # XYZ Química - 3 setores, 3 cargos cada
        {"empresa": "XYZ Química", "setor": "Laboratório", "cargo": "Técnico", "atividade": "Análises químicas", "ambiente": "Laboratório", "agentes": [{"agente": "Solventes", "concentracao": "20 ppm", "exposicao": "6h", "analise": "Controlado", "medidas_existentes": "Capela", "medidas_necessarias": "Monitoramento"}], "parecer": "Sistema adequado", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:00:00"},
        {"empresa": "XYZ Química", "setor": "Laboratório", "cargo": "Analista", "atividade": "Controle de qualidade", "ambiente": "Sala de análises", "agentes": [{"agente": "Ácidos", "concentracao": "2 ppm", "exposicao": "4h", "analise": "Baixo", "medidas_existentes": "Ventilação", "medidas_necessarias": "EPI"}], "parecer": "Condições seguras", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:01:00"},
        {"empresa": "XYZ Química", "setor": "Laboratório", "cargo": "Supervisor", "atividade": "Supervisão laboratorial", "ambiente": "Escritório do lab", "agentes": [{"agente": "Vapores", "concentracao": "5 ppm", "exposicao": "2h", "analise": "Baixo", "medidas_existentes": "Isolamento", "medidas_necessarias": "Ventilação"}], "parecer": "Ambiente controlado", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:02:00"},
        
        {"empresa": "XYZ Química", "setor": "Produção", "cargo": "Operador", "atividade": "Operação de reatores", "ambiente": "Área de produção", "agentes": [{"agente": "Vapores químicos", "concentracao": "15 ppm", "exposicao": "8h", "analise": "Médio", "medidas_existentes": "Respirador", "medidas_necessarias": "Exaustão"}], "parecer": "Necessário melhorar", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:03:00"},
        {"empresa": "XYZ Química", "setor": "Produção", "cargo": "Técnico", "atividade": "Controle de processo", "ambiente": "Sala de controle", "agentes": [{"agente": "Temperatura", "concentracao": "28°C", "exposicao": "8h", "analise": "Alto", "medidas_existentes": "Ar condicionado", "medidas_necessarias": "Manutenção"}], "parecer": "Controle térmico", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:04:00"},
        {"empresa": "XYZ Química", "setor": "Produção", "cargo": "Encarregado", "atividade": "Coordenação da produção", "ambiente": "Escritório produção", "agentes": [{"agente": "Ruído", "concentracao": "70 dB", "exposicao": "6h", "analise": "Aceitável", "medidas_existentes": "Isolamento", "medidas_necessarias": "Monitoramento"}], "parecer": "Situação estável", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:05:00"},
        
        {"empresa": "XYZ Química", "setor": "Segurança", "cargo": "Técnico", "atividade": "Segurança do trabalho", "ambiente": "Toda a empresa", "agentes": [{"agente": "Diversos", "concentracao": "Variável", "exposicao": "8h", "analise": "Controlado", "medidas_existentes": "EPIs", "medidas_necessarias": "Treinamentos"}], "parecer": "Programa efetivo", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:06:00"},
        {"empresa": "XYZ Química", "setor": "Segurança", "cargo": "Engenheiro", "atividade": "Engenharia de segurança", "ambiente": "Escritório técnico", "agentes": [{"agente": "Ergonomia", "concentracao": "N/A", "exposicao": "8h", "analise": "Bom", "medidas_existentes": "Mobiliário", "medidas_necessarias": "Avaliação"}], "parecer": "Condições adequadas", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:07:00"},
        {"empresa": "XYZ Química", "setor": "Segurança", "cargo": "Inspetor", "atividade": "Inspeção de segurança", "ambiente": "Áreas operacionais", "agentes": [{"agente": "Riscos diversos", "concentracao": "Variável", "exposicao": "6h", "analise": "Monitorado", "medidas_existentes": "Procedimentos", "medidas_necessarias": "Auditorias"}], "parecer": "Sistema robusto", "responsavel": "Eng. Santos", "data_criacao": "14/12/2024 14:08:00"},

        # DEF Construção - 3 setores, 3 cargos cada
        {"empresa": "DEF Construção", "setor": "Obra", "cargo": "Pedreiro", "atividade": "Alvenaria", "ambiente": "Canteiro", "agentes": [{"agente": "Poeira", "concentracao": "8 mg/m³", "exposicao": "8h", "analise": "Alto", "medidas_existentes": "Máscara", "medidas_necessarias": "Umidificação"}], "parecer": "Controle necessário", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:00:00"},
        {"empresa": "DEF Construção", "setor": "Obra", "cargo": "Carpinteiro", "atividade": "Carpintaria", "ambiente": "Área de madeira", "agentes": [{"agente": "Serragem", "concentracao": "5 mg/m³", "exposicao": "8h", "analise": "Médio", "medidas_existentes": "Aspiração", "medidas_necessarias": "EPI"}], "parecer": "Sistema eficiente", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:01:00"},
        {"empresa": "DEF Construção", "setor": "Obra", "cargo": "Armador", "atividade": "Armação de ferro", "ambiente": "Pátio de armação", "agentes": [{"agente": "Cortes", "concentracao": "N/A", "exposicao": "8h", "analise": "Risco", "medidas_existentes": "Luvas", "medidas_necessarias": "Treinamento"}], "parecer": "Atenção aos EPIs", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:02:00"},
        
        {"empresa": "DEF Construção", "setor": "Escritório", "cargo": "Engenheiro", "atividade": "Projetos", "ambiente": "Escritório", "agentes": [{"agente": "Ergonomia", "concentracao": "N/A", "exposicao": "8h", "analise": "Bom", "medidas_existentes": "Cadeira ergonômica", "medidas_necessarias": "Pausas"}], "parecer": "Ambiente saudável", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:03:00"},
        {"empresa": "DEF Construção", "setor": "Escritório", "cargo": "Arquiteto", "atividade": "Desenhos técnicos", "ambiente": "Sala de projetos", "agentes": [{"agente": "Iluminação", "concentracao": "600 lux", "exposicao": "8h", "analise": "Adequado", "medidas_existentes": "Iluminação natural", "medidas_necessarias": "Complementar"}], "parecer": "Condições ideais", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:04:00"},
        {"empresa": "DEF Construção", "setor": "Escritório", "cargo": "Administrativo", "atividade": "Atividades administrativas", "ambiente": "Escritório geral", "agentes": [{"agente": "Ar condicionado", "concentracao": "22°C", "exposicao": "8h", "analise": "Adequado", "medidas_existentes": "Climatização", "medidas_necessarias": "Manutenção"}], "parecer": "Ambiente confortável", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:05:00"},
        
        {"empresa": "DEF Construção", "setor": "Equipamentos", "cargo": "Operador", "atividade": "Operação de máquinas", "ambiente": "Pátio de equipamentos", "agentes": [{"agente": "Vibração", "concentracao": "4 m/s²", "exposicao": "6h", "analise": "Alto", "medidas_existentes": "Assento", "medidas_necessarias": "Rodízio"}], "parecer": "Controle de vibração", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:06:00"},
        {"empresa": "DEF Construção", "setor": "Equipamentos", "cargo": "Mecânico", "atividade": "Manutenção de máquinas", "ambiente": "Oficina móvel", "agentes": [{"agente": "Óleo hidráulico", "concentracao": "3 mg/m³", "exposicao": "6h", "analise": "Controlado", "medidas_existentes": "Ventilação", "medidas_necessarias": "EPI"}], "parecer": "Situação controlada", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:07:00"},
        {"empresa": "DEF Construção", "setor": "Equipamentos", "cargo": "Supervisor", "atividade": "Supervisão de equipamentos", "ambiente": "Campo", "agentes": [{"agente": "Sol", "concentracao": "UV alto", "exposicao": "8h", "analise": "Alto", "medidas_existentes": "Protetor solar", "medidas_necessarias": "Cobertura"}], "parecer": "Proteção solar", "responsavel": "Eng. Costa", "data_criacao": "13/12/2024 09:08:00"}
    ]
}

# Salvar dados hierárquicos
with open('dados_riscos.json', 'w', encoding='utf-8') as f:
    json.dump(dados_hierarquicos, f, ensure_ascii=False, indent=2)

print("Dados hierárquicos criados com sucesso!")
print("27 registros criados:")
print("- ABC Indústria: 9 registros (3 setores x 3 cargos)")
print("- XYZ Química: 9 registros (3 setores x 3 cargos)")  
print("- DEF Construção: 9 registros (3 setores x 3 cargos)")